repos:
-   repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort
        args: [--in-place]
-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        language_version: python3
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
