import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const { version } = JSON.parse(readFileSync('package.json', 'utf8'));
const out = `// Generated by scripts/set-version.mjs — do not edit manually.\nexport const version = '${version}';\n`;

mkdirSync('src/environments', { recursive: true });
writeFileSync('src/environments/version.ts', out);
console.log(`Version set to ${version}`);
