# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import glob
import os
import sys

sys.path.insert(0, os.path.abspath(".."))

import undertale

# -- Project information -----------------------------------------------------

project = undertale.__title__
copyright = undertale.__copyright__
author = undertale.__author__
release = undertale.__version__

# -- General configuration ---------------------------------------------------

extensions = ["sphinx.ext.autodoc", "sphinx.ext.autosummary", "sphinx.ext.napoleon"]

exclude_patterns = ["_build"]

# -- Options for HTML output -------------------------------------------------

html_theme = "alabaster"
html_theme_options = {
    "show_relbar_bottom": True,
}
html_show_sphinx = False

# -- Extension configuration -------------------------------------------------

autodoc_member_order = "bysource"
autodoc_default_options = {
    "show-inheritance": None,
    "members": None,
}
autosummary_generate = True

# -- Custom modifications ----------------------------------------------------

REFERENCE = os.path.join(os.path.dirname(__file__), "_undertale")


def shorten_autosummary_titles(app):
    """Shorten autosummary-generated stubs to simplify display."""

    autogenerated = glob.glob(os.path.join(REFERENCE, "*.rst"))

    for path in autogenerated:
        with open(path, "r") as f:
            lines = f.readlines()

        if not lines:
            continue

        title = lines[0].strip().split(".")[-1]

        lines[0] = f"{title}\n"
        lines[1] = "=" * len(title) + "\n"

        with open(path, "w") as f:
            f.writelines(lines)


def setup(app):
    app.connect("builder-inited", shorten_autosummary_titles)
