name: Commit

on: [push]

jobs:
  Lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development] -c constraints.txt
      - name: Lint
        run: |
          isort --check ./
          black --check ./
          flake8 ./
