name: Merge

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[development] -c constraints.txt
      - name: Build Documentation
        run: |
          sphinx-build -W -b html docs build/documentation
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: build/documentation
          exclude_assets: .gitignore
