name: Pull Request

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopen, edited]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          bash .github/workflows/scripts/conventional.sh "$TITLE"
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.12'
          activate-environment: undertale
          environment-file: environment.yml
      - name: Develop
        run: |
          conda env update -f environment.development.yml
      - name: Test
        run: |
          conda run -n undertale python tests/unit.py --verbose
