name: Pull Request

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopen, edited]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          bash .github/workflows/scripts/conventional.sh "$TITLE"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development] -c constraints.txt
